name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Workflow Dispatched Successfully"
      - name: End Message
        run: echo "Workflow closing..."
