name: Test And Deploy
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying Application"